### PR TITLE
Python 3 compatibility; flake8 compatibility; numerous small fixes

### PR DESCRIPTION
**Pull request by adamhadani**
This PR contains various fixes to make the package more maintainable, specifically making it PEP8 (flake8) compliant, and fixes some Python 3 compatibility issues (e.g as noted in Issue #16). 

Main changes:
- Rename 'SQLAlchemy' file to 'store', fixing the issue raised in #16 for Python 3
- Use the standard Python 2/3 compatibility library [six](https://pythonhosted.org/six/) to replace conditional logic in multiple places in code (added six as dependency)
- Remove deprecated pip '--use-mirrors' flag from Travis CI config file (this was removed from pip in 7.0.0: https://pip.pypa.io/en/stable/news/#release-notes)
- added 'setuptools' explicitly to requirements-py{2,3}.txt files as Travis CI builds were failing due to an out of date version
- Make code [flake8](http://flake8.pycqa.org/en/latest/index.html) compliant, re-shuffle some imports to adhere to PEP8 conventions and alphabetize them, also moving some imports that were nested in functions to top of files
- Rename all files to be lowercase, being more uniform and avoiding issues with some OSes having trouble with case-sensitive filenames
- Standardized on using double quotes everywhere in code - had a mix of single and double previously
- Some cleanup in setup.py to try and make it less redundant / more readable - I think a big refactoring of this file is imminent..

Verified all unit-tests passed on TravisCI after changes

### CODE REVIEW

**Comment by adamhadani** [comment]
ping @gjhiggins for your kind consideration! would love to try and use this package but currently is broken for Python 3. This PR fixes the immediate issues, but I am also wondering whether there are any plans to maintain this package viz-a-viz updates to core rdflib 4.x/5.x

**Comment by adamhadani** [comment]
ping @gjhiggins any feedback appreciated on this!

**Comment by gjhiggins** [comment]
Thanks for the fix and the spruce-up.

**Comment by cwilkes** [comment]
Awesome, thanks for doing this!

**Pull request merged**
