### PR TITLE
Fixed a bug where empty prefix could not be retrieved while they were stored

### PR DESCRIPTION
**Pull request by PonteIneptique**
See issue https://github.com/RDFLib/rdflib-sqlalchemy/issues/37

Added my name to Contributors as it seemed to be the process.

Let me know if I can do anything more

### CODE REVIEW

**Comment by gjhiggins** [comment]
I did some housekeeping to try and get the Travis CI build to pass - which revealed a Py2.7 unicode issue and a(n unresolved) Python2.7/MySQL issue: https://travis-ci.org/gjhiggins/rdflib-sqlalchemy-tmp/builds/339733768

**Comment by PonteIneptique** [comment]
Hi @gjhiggins 
Should I take on those two separate issues in this PR ?

**Comment by PonteIneptique** [comment]
So I ran the test locally, setting the database first with `CREATE DATABASE IF NOT EXISTS test'` from the `.travis.yml` and connecting through `mysql+mysqldb://test@localhost/test?charset=utf8` : it failed at inserting the Japanese characters.
I did an ALTER Schema after that and it worked wonders... I am pushing this changed too see if Travis will accept this

**Comment by PonteIneptique** [comment]
The change seems to work fine now. I assume there was some update of the MySQL part (either server on Travis or mysql client) that would not adapt to the character set. This way, the tests pass as they should.

**Comment by PonteIneptique** [comment]
I might add : sorry for the double commit as I forgot \` is not working well in CLI

**Comment by PonteIneptique** [comment]
Hi @adamhadani and @gjhiggins , any chance this could be merged and we could get an upgraded version on pypi ?

**Comment by PonteIneptique** [comment]
Hey guys,
It's been some time the PR is there and it seemed to have been approved :) Just wanted to ping you back on this :) Thanks !

**Comment by PonteIneptique** [comment]
Just pinging if someone still works on this repo :)

**Comment by PonteIneptique** [comment]
Hi @mwatts15 :) Good news then !
I am a bit confused because the bare except were already bare before I came in :/ So I would not know what to do to be fair. Anyway, thanks for maintaining ;)

**Comment by mwatts15** [comment]
Rebased and merged in #46

**Comment by PonteIneptique** [comment]
I did not say it before but it seems important: thank you @mwatts15

**Pull request closed without merging**
